version: '3'

services:
  db:
    image: mysql:5.7
    volumes:
      - ../db_files:/var/lib/mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: toor
    ports:
      - 3306:3306

  php:
    depends_on:
      - db
    image: php:7.1
    build:
      context: .
      dockerfile: Dockerfile
    links:
      - db
    volumes:
      - ../www:/var/www/html
      - ./php.ini:/usr/local/etc/php/conf.d/php.ini
      - ./virtualhost-php.conf:/etc/apache2/sites-available/001-virtualhost-php.conf
      - ../logs/error.log:/var/www/error.log
      - ../logs/access.log:/var/www/access.log
    environment:
      DB_HOST: db:3306
      DB_PASSWORD: toor
    ports:
      - 80:80
